// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5C1yjSElJcOx4-7fi0YpMPJ978cEIP6g',
    appId: '1:986012308022:web:17a678e09bef723a55be97',
    messagingSenderId: '986012308022',
    projectId: 'todo-ab958',
    authDomain: 'todo-ab958.firebaseapp.com',
    storageBucket: 'todo-ab958.appspot.com',
    measurementId: 'G-6TY560WHJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrcQu3w8laUg4oV8T6H34XnMa6mZkm84M',
    appId: '1:986012308022:android:66f66e3979b1427a55be97',
    messagingSenderId: '986012308022',
    projectId: 'todo-ab958',
    storageBucket: 'todo-ab958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMM8DmLXaBfF9gL60vUGCqyh2yUB931RA',
    appId: '1:986012308022:ios:03f2b7a3f491adbc55be97',
    messagingSenderId: '986012308022',
    projectId: 'todo-ab958',
    storageBucket: 'todo-ab958.appspot.com',
    iosClientId: '986012308022-ak0rp9vb42majlvhopstl1dpih80ka01.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMM8DmLXaBfF9gL60vUGCqyh2yUB931RA',
    appId: '1:986012308022:ios:03f2b7a3f491adbc55be97',
    messagingSenderId: '986012308022',
    projectId: 'todo-ab958',
    storageBucket: 'todo-ab958.appspot.com',
    iosClientId: '986012308022-ak0rp9vb42majlvhopstl1dpih80ka01.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
